{
    'name': 'Hospital Managment',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'By Hana',
    'summary': 'Hospital managment system',
    'sequance': -100,
    'description': """Hospital managment system""",
    'depends': [],
    'data': [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/patient_view.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'asset': {},
}
